# deploy-prod.yml - Production-specific deployment workflow
name: Deploy to Production

on:
  push:
    tags:
      - 'prod-*'     # Production tags (prod-1.2.3)
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to deploy (optional)'
        required: false
        default: ''

jobs:
  deploy:
    uses: ./.github/workflows/deploy.yml
    with:
      environment: prod
      service_name: my-service
      repository: ${{ github.repository }}
      # Optional: override these if defaults don't work for your project
      # wrangler_config: wrangler.prod.toml
      # build_command: npm run build:prod
      node_version: '22.15.1'
      workers_domain: 'my-domain.workers.dev'
      # For production, you might want to use a different URL pattern, e.g., with a custom domain
      # deployment_url_pattern: 'https://app.example.com'
      deployment_url_pattern: 'https://{service_name}-{environment}.{domain}'
      # You might want to enforce stricter security scanning for production
      run_security_scan: true
    secrets:
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
